float32 expect_z                # m
float32 z_noise                 # m
uint8 smooth_window             # 0~5
float32[3] max_acceleration     # m/s^2
bool output_tag_pos
bool output_anchor_packet
bool output_anchor_pos
bool output_anchor_link_data
bool output_anchor_signal
bool output_anchor_ddoa
bool output_tag_pos_even_error
bool output_anchor_link_status
uint8 sniff_duty_cycle          # 1~100
uint8 update_interval_max       # s
uint16 reset_interval           # s
